name       : mozjs
version    : 60.6.1
release    : 8
source     :
    - https://hg.mozilla.org/mozilla-unified/archive/FIREFOX_60_6_1esr_RELEASE.tar.gz : 902b61407497d24d50ad8defbb9b45d47ae865d3b00fb31211d666c4f916b028
homepage   : http://mozilla.org
license    :
    - GPL-2.0
    - MPL-1.1
component  : desktop.library
strip      : no
summary    : JS is Mozilla's JavaScript engine written in C/C++
description: |
    JS is Mozilla's JavaScript engine written in C/C++
builddeps  :
    - autoconf213
setup      : |
    export PYTHON=/usr/bin/python2
    %apply_patches
    head -n -1 config/milestone.txt > config/milestone.txt
    echo "${version}" >> config/milestone.txt
    autoconf213
    mkdir $workdir/building
    cd $workdir/building
    ../js/src/%configure \
        --disable-debug \
        --disable-debug-symbols \
        --disable-jemalloc \
        --disable-strip \
        --enable-posix-nspr-emulation \
        --enable-readline \
        --enable-release \
        --enable-threadsafe \
        --enable-shared-js \
        --enable-tests
build      : |
    export PYTHON=/usr/bin/python2
    cd $workdir/building
    %make
install    : |
    export PYTHON=/usr/bin/python2
    cd $workdir/building
    %make_install
    rm -r $installdir/%libdir%/*.ajs
