name       : mozjs
version    : 52.4.0
release    : 3
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/52.4.0esr/source/firefox-52.4.0esr.source.tar.xz : 58ae7cb6c2fb81d22762ab3c60e46cadbe7c5b687f24c2823d9533ec998a21ee
homepage   : http://mozilla.org
license    :
    - GPL-2.0
    - MPL-1.1
component  : desktop.library
summary    : JS is Mozilla's JavaScript engine written in C/C++
description: |
    JS is Mozilla's JavaScript engine written in C/C++
libsplit   : no
builddeps  :
    - pkgconfig(nspr)
    - autoconf213
setup      : |
    export PYTHON=/usr/bin/python2
    %apply_patches
    head -n -1 config/milestone.txt > config/milestone.txt
    echo "${version}" >> config/milestone.txt
    cd $workdir/js/src
    autoconf213
    %configure --enable-readline \
               --enable-threadsafe \
               --enable-shared-js \
               --with-system-nspr
build      : |
    export PYTHON=/usr/bin/python2
    cd $workdir/js/src
    %make
install    : |
    export PYTHON=/usr/bin/python2
    cd $workdir/js/src
    %make_install
    rm -r $installdir/%libdir%/*.ajs
