name       : mozjs
version    : 68.6.0
release    : 9
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/68.6.0esr/source/firefox-68.6.0esr.source.tar.xz : 2428213ceb75cb6772b3044d9c14870d1ae5b0161379aeb29248650e13761c9f
homepage   : http://mozilla.org
license    :
    - GPL-2.0-or-later
    - MPL-1.1
component  : desktop.library
summary    : JS is Mozilla's JavaScript engine written in C/C++
description: |
    JS is Mozilla's JavaScript engine written in C/C++
strip      : no
libsplit   : no
builddeps  :
    - autoconf213
    - cargo
    - llvm-clang
environment : |
    export AR=llvm-ar
    export NM=llvm-nm
    export RANLIB=llvm-ranlib
setup      : |
    export PYTHON=/usr/bin/python2
    %apply_patches
    head -n -1 config/milestone.txt > config/milestone.txt
    echo "${version}" >> config/milestone.txt
    autoconf213
    mkdir $workdir/building
    cd $workdir/building
    ../js/src/%configure \
        --disable-debug \
        --disable-debug-symbols \
        --disable-jemalloc \
        --disable-strip \
        --disable-tests \
        --enable-optimize \
        --enable-posix-nspr-emulation \
        --enable-readline \
        --enable-release \
        --enable-shared-js \
        --enable-unaligned-private-values \
        --with-system-zlib \
        --without-system-icu
build      : |
    export PYTHON=/usr/bin/python2
    cd $workdir/building
    %make
install    : |
    export PYTHON=/usr/bin/python2
    cd $workdir/building
    %make_install
    rm -r $installdir/%libdir%/*.ajs
