name       : mozjs
version    : 102.0.1
release    : 20
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/102.0.1esr/source/firefox-102.0.1esr.source.tar.xz : 98cdfeaeb2c567dbe88300bdf4febc41b3a400f446a4bd5be99a1fd09ec5cb1a
homepage   : http://mozilla.org
license    :
    - GPL-2.0-or-later
    - MPL-1.1
component  : desktop.library
summary    : JS is Mozilla's JavaScript engine written in C/C++
description: |
    JS is Mozilla's JavaScript engine written in C/C++
strip      : no
libsplit   : no
networking : yes
builddeps  :
    - pkgconfig(icu-uc)
    - autoconf213
    - cargo
    - llvm-clang
environment: |
    export AR=llvm-ar
    export NM=llvm-nm
    export RANLIB=llvm-ranlib
setup      : |
    %apply_patches
    head -n -1 config/milestone.txt > config/milestone.txt
    echo "${version}" >> config/milestone.txt

    mkdir $workdir/building
    cd $workdir/building

    autoconf -o ../js/src/configure ../js/src/configure.in
    ../js/src/%configure \
        --disable-debug \
        --disable-debug-symbols \
        --disable-jemalloc \
        --disable-strip \
        --disable-tests \
        --enable-optimize \
        --enable-posix-nspr-emulation \
        --enable-readline \
        --enable-release \
        --enable-shared-js \
        --enable-unaligned-private-values \
        --with-system-zlib \
        --with-system-icu
build      : |
    cd $workdir/building
    %make
install    : |
    cd $workdir/building
    %make_install
    rm -r $installdir/%libdir%/*.ajs
